### PR TITLE
Improve listening data page & revamp styling

### PR DESCRIPTION
**Pull request by notsoli**
Made a number of improvements to the listening data page:
* Added table headers
* Removed the ugly border around entries
* Added song duration and total plays
* If users listened to the same song multiple times in a row, compressed them to one entry and displayed the number of repetitions
* Changed column widths to better reflect mockup
* Sorted songs by most recently listened

Some future improvements:
* Adding tests for the `processSongs` function
* Adding unit tests
* Adding pagination

### CODE REVIEW

**Review by ibixler — COMMENTED** [review]
when the window is small the formatting gets a little messed up

the collumns stop ligning up on plays and duration

we might want to add some separators to make the data eaiser to follow

**Review by michibatoryu — COMMENTED** [review]
Looks good, I guess my only concern UI-side is the differentiation between repetitions and total plays. Maybe switch the 'play' column to be 'total plays' and have a little repeat icon instead of an 'X' next to repeated track numbers? Very lit tho

**Review by notsoli — COMMENTED** [review]
Fixed headers/columns not lining up and improved scroll behavior to be more webapp-like. Added the repeat icon, but keeping the "plays" column titled as-is because i fear "total plays" would take up too much space for how small the actual column content is.

**Review by ibixler — COMMENTED** [review]
we need to remember to add the new field when we merge #46 (i think thats the right pr number lul its the one where we are gonna move that data type into the other thing

**Pull request merged**
