### PR TITLE
frontend spotify login component and de-duplication

### PR DESCRIPTION
**Pull request by ibixler**
this pr adds support for:
* users deleting themselves and all their data
* users re-linking and unlinking spotify
* adds small settings menu

Also, 
this pr puts song and album data in a global lib folder at the base of the repo

### CODE REVIEW

**Comment by ibixler** [comment]
there are new env rules see slack

**Review by notsoli — APPROVED** [review]
After adding the new .env variable, everything works on my end! Here's what I tested:
* Cleaned out a bunch of users I've made during testing
* Made sure their profiles, Spotify tokens, profiles, and associated tracks are removed from the database
* Unlinked and relinked my Spotify account, making sure the entries were removed & repopulated in the database
* Played around with the settings dropdown

**Comment by notsoli** [comment]
wow this fixes like a billion issues lol

**Comment by ibixler** [comment]
lul thanks for adding the fixes things things iykyk 

am i good to go ahead and merge this?

**Comment by notsoli** [comment]
yeah for sure, gl with the conflicts teehee

**Pull request merged**
