### PR TITLE
frontend: Profile page glowup

### PR DESCRIPTION
**Pull request by notsoli**
Here's what I did:
* Make styling reflect mockup
* Add a default profile photo
* Add ability to reset listening history
* Add ability to reset profile information
* Initialize profile information
* Add graceful error handing for all form actions (through progressive form enhancement or otherwise)
* Check if “reset profile information” actually removed any info and inform user if it didn’t
* Write test cases for frontend
* Add error handling in DeleteUser component, sending users to `/profile` if the delete was unsuccessful
* Make DeleteUser more customizable, taking advantage of `<slot />`s
* Fix the old issue where no listening data would result in a 500 error

And a few things to do in the future:
* Replace default profile photo with users' Spotify avatar
* Implement that cute rotating circular text thing
* Write test cases for the reset-listening-data edge function

### CODE REVIEW

**Review by ibixler — COMMENTED** [review]
maybe the spec files should be moved to a test directory

**Review by ibixler — COMMENTED** [review]
appwoved

**Review by ibixler — COMMENTED** [review]
i added 1 commit fixing something with spotify

**Comment by ibixler** [comment]
> appwoved

actually the delete listening data isnt quite working right

**Comment by notsoli** [comment]
oop in what way
rn it just deletes data in the songs-played table but doesn't scrub songs and albums that now aren't linked to anything anymore
i imagine there's a way to do that using sql but

**Comment by ibixler** [comment]
> oop in what way rn it just deletes data in the songs-played table but doesn't scrub songs and albums that now aren't linked to anything anymore i imagine there's a way to do that using sql but

(in promise) TypeError: Cannot read properties of null (reading 'success')
    at HTMLButtonElement.resetListeningHistory (+page.svelte:59:14)
    
    this is what i see, im on main on supabase and delete account works

**Comment by ibixler** [comment]
> > oop in what way rn it just deletes data in the songs-played table but doesn't scrub songs and albums that now aren't linked to anything anymore i imagine there's a way to do that using sql but
> 
> this is what i see, im on main on supabase and delete account works
> 
> (in promise) TypeError: Cannot read properties of null (reading 'success') at HTMLButtonElement.resetListeningHistory (+page.svelte:59:14)

okokokokok i got it to work by checking out the supabase branch lul

**Pull request merged**
